### ISSUE TITLE
Api issue when htsp exceeds clsp

### ISSUE THREAD

**Issue by rcjcarr** [grivkees/homebridge-carrier-infinity#207]
**Describe The Bug:**
Hi Glenn, thanks so much again for your efforts on this plugin. v1.5.12 is just great.

There is still a slight issue that pops-up once in a while. I dial-up a new temperature on my iPhone (via the Home app), and the Homebridge Plugin reports the usual:
```
[24/03/2022, 06:00:02] [CarrierInfinity] Pushing changes to carrier api...
[24/03/2022, 06:00:09] [CarrierInfinity] Changes sent to carrier api successfully.
```
but the Carrier Server does not appear to get updated as evidenced by temperature setpoint reported by the Carrier-Infinity Website (https://www.myinfinitytouch.carrier.com/login). 

If I turn my iPhone off completely and reboot my Homepod mini,  and power-up my iPhone after, everything syncs up again. So this could be a Homekit or Homebridge issue and not an issue with your plugin. I was also wondering if other apps on my phone which have access to Homekit data  (Home Controller for Homekit, EVE, and Home+ 5) could also cause such an ambiguity. Could also be an issue with the Carrier server; I noticed temperature changes commanded through the IOS app sometimes take a minute or two to be reflected on the Carrier-Infinity webiste.

Any comments appreciated.

**To Reproduce:**
Multiple temperature changes in relatively  close succession seems to induce this.

**Expected behavior:**
Carrier API temperature setpoint to be updated as per iPhone/Homebridge settings.

**Logs:**
(Nothing ususual)

**Plugin Config:**
homebridge-carrier-infinity v1.5.12`
```json
{
    "username": "xxxxxxxxxxx",
    "password": "xxxxxxxxxx",
    "holdBehavior": "forever",
    "showOutdoorTemperatureSensor": true,
    "showFanControl": true,
    "showIndoorHumiditySensors": true,
    "platform": "CarrierInfinity"
}
```

**Environment:**
* **Plugin Version**: homebridge-carrier-infinity v1.5.12
* **Homebridge Version**: 1.4.0
* **Node.js Version**: v16.14.0
* **NPM Version**: v8.5.5
* **Operating System**:  Raspbian GNU/Linux Bullseye (11)

Regards,
Raymond Carr

**Comment by grivkees** [comment]
Really glad to hear the new version is working out well!

So if you see the message “Changes sent to carrier api successfully” that actually means that the plug-in went and checked the carrier api and confirmed the changes it pushed actually showed up. (There’s a warning generated if it can’t confirm, or if it saw different values from the carrier api)

That said, I’ve definitely seen this before. Specifically I’ve seen a change get “accepted” by the carrier website, but then disappear shortly after for no clear reason.

My best guess is that the thermostat itself is pushing an update of its current status to the carrier api, and carrier decides that update is “newer” and it should keep that one instead. The only evidence I have for this is that if I happen to touch my thermostat, even without making any changes, shortly after I make a HomeKit change, the HomeKit imitated change sometimes seems to disappear from carrier.

There is definitely something here though I hope to dig into deeper at some point.

**Comment by grivkees** [comment]
1.5.13 should fix this issue, give it a shot and let me know if youre still seeing this issue. thanks!
