### ISSUE TITLE
Resume Zone Schedule Option

### ISSUE THREAD

**Issue by tedinorbit** [grivkees/homebridge-carrier-infinity#245]
Similar to hitting "per schedule" on your thermostat, create a switch per zone that resets any manual holds to the scheduled activities.

**Describe the solution you'd like:**
For each zone, create a switch that is "on" when the default schedule for that zone is being followed, and is "off' when anything deviates from it (timed hold, permanent hold, vacation mode(?)). This can be grouped with the thermostat and fan objects on a per zone basis.

**Additional context:**
In the "config" object in the api, this can be determined by looking at the "holdActivity", "hold", and "otmr" values. If I recall correctly, you can reset holdActivity to an empty string, hold to "off" and otmr to an empty string.

**Comment by tedinorbit** [comment]
For reference, this is a screenshot of the function desired from the thermostat interface
![IMG_2118](https://user-images.githubusercontent.com/35117017/170124863-3b12e8ae-88de-41db-b653-0ebe61f67392.jpg)
.

**Comment by tedinorbit** [comment]
Just tried it out, looks great! Thank you!

**Comment by grivkees** [comment]
Awesome! You're welcome!

I'll release it as the stable version in the next week or so. Theres a few things I want to do first to make the syncing between the activity buttons work better.
