### ISSUE TITLE
Unexpected 'OFF' mode fan speed interaction

### ISSUE THREAD

**Issue by rcjcarr** [grivkees/homebridge-carrier-infinity#248]
**Describe The Bug:**
Commanding a Manual Fan mode with a speed of 0% results in the fan actually being set to medium speed.

**To Reproduce:**
Set fan mode to OFF using carrier MyInfinity IOS app. Fan state is reported as 'OFF' in carrier web interface/web portal. Change fan MODE to OFF (either using HB Accessories/Home App/Controller for Home app/ Home+) and it actually goes to MEDIUM speed instead of the expected OFF state, and is reported as being on MEDIUM speed in the MyInfinity portal and/or app.

**Expected behavior:**

Fan should be off and be reported as such.

**Logs:**

No errors reported.

**Plugin Config:**

```json
   {
            "username": "*****r",
            "password": "*****",
            "holdBehavior": "forever",
            "showOutdoorTemperatureSensor": true,
            "showFanControl": true,
            "showIndoorHumiditySensors": true,
            "platform": "CarrierInfinity"
        },
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/50344858/170986648-90c0b147-f87a-4e8b-bd20-daf1d00a099b.png)

**Environment:**

* **Plugin Version**: v1.5.12
* **Homebridge Version**: 1.4.1
* **Node.js Version**:  v16.15.0
* **NPM Version**: 8.5.5
* **Operating System**: Raspbian

**Comment by grivkees** [comment]
@rcjcarr theres a few different ways to turn a fan off. Are you doing a straight toggle by clicking the fan icon, or setting the speed to 0, or pressing the auto/manual toggle?

**Comment by grivkees** [comment]
Closing as can not reproduce. Feel free to reopen if you see this and you are still having the issue. Just let me know how exactly you are turning off the fan in HK, and I can look deeper.
