### ISSUE TITLE
Enable logging of API request and response details

### ISSUE THREAD

**Issue by Adam-S-Daniel** [grivkees/homebridge-carrier-infinity#313]
**Is your feature request related to a problem? Please describe:**
When troubleshooting HomeKit automations involving this plug-in, its log entries often lack sufficient information regarding to determine what is happening.

**Describe the solution you'd like:**
I would like to be able to specify a higher level of logging verbosity for this plug-in in the HomeKit config file. When I do so, I would like e.g.:
  -  _“Changes may not have successfully propagated to the carrier API“_ to be followed by the API request URL, verb, body (if applicable); and the API response HTTP code (e.g. `500`) and body. 
  -  _“Pushing changes to carrier API“_ to be followed by which changed value(s) triggered the push

**Describe alternatives you've considered:**
I would have to employ some kind of packet sniffing solution without this, and then would have to filter out and correlate results. This would not be practical for ongoing maintenance of HomeKit automations involving my home’s air-conditioning systems.

**Additional context:**
This is in support of HomeKit automations I use to set my upstairs and downstairs AC systems to Away and back to Schedule based on occupancy sensors on the corresponding floors. When I find, for example, that a system is still set to Away even though the corresponding floor is occupied, I am unable to determine exactly what has gone wrong. The ability to log information as specified above would almost certainly allow me to determine the problem in such instances, greatly speeding the process of making automations work as intended more reliably.

**Comment by Adam-S-Daniel** [comment]
This issue and #312 are complimentary. I separated them because they have fairly different levels of effort to implement, and are also independently useful.

**Comment by grivkees** [comment]
It turns out the plugin was silently swallowing all http errors before... Fixed that and generally made error handling better and more detail should show in console, especially if you have your homebridge in debug mode (option in the homebridge settings).
Let me know how the new build here works for you. Thanks for opening this!
