### ISSUE TITLE
Comfort Activity Switch Name

### ISSUE THREAD

**Issue by grivkees** [grivkees/homebridge-carrier-infinity#385]
Looks like HK behavior is different with new iOS. Need to fix something to make switch name show activity name, and not "[ZONE] Comfort Activity".

**Comment by MatthewNrmOK** [comment]
I am still experiencing this issue on iOS 17.0.2, macOS 14.0 (23A344)

Carrier Infinity: 
System Control Model # SYSTXCCWIC01-B
System Control Firmware Version CESR131626-04.47

I have had some luck with identifying labels but the hold function seems to change their behavior and it cannot be reverted within HomeKit. Using the Carrier Infinity app does work as expected.

**Comment by grivkees** [comment]
The switches are significantly improved on 1.6.13 or later. Give it a try, and feel free to reopen (or make a new issue) if you're still experiencing issues.
