### ISSUE TITLE
Support for Filter characteristics

### ISSUE THREAD

**Issue by ekobres** [grivkees/homebridge-carrier-infinity#4]
**Is your feature request related to a problem? Please describe:**
Current accessory doesn't support filter functionality.

**Describe the solution you'd like:**
Implement the filter characteristics, which adds sensors and a filter reset switch to the home app and allows you to ask siri questions about the filter life or to let the system know the filter was changed.

The following HomeKit Characteristics apply: 

HMCharacteristicTypeFilterLifeLevel - The amount of useful life remaining in a filter.
HMCharacteristicTypeFilterChangeIndication - A filter’s change indicator.
HMCharacteristicTypeFilterResetChangeIndication - A reset control for a filter change notification.

These characteristics should be able to be enabled or disabled in the configuration.

**Describe alternatives you've considered:**
N/A

**Additional context:**

**Comment by grivkees** [comment]
In progress in https://github.com/grivkees/homebridge-carrier-infinity/tree/filtersupport

The homebridge api and HomeKit api expectations seem to mismatch though, and homebridge is throwing errors when HomeKit is happy, and HomeKit doesn’t work when homebridge is happy. Need to investigate further.

**Comment by grivkees** [comment]
FilterLifeLevel and FilterResetChangeIndication landed a while ago.

It doesn't look like the Carrier api supports sending a reset filter life level via the api. Not even their first party apps let you do it, it looks like it may only be possible on the thermostat itself.

(Also, it doesn't look like the default Home app would even show a reset button if it did.)

If you find any support in the carrier api, let me know and I'd add support for using it, it even if the default home app couldn't use it. But for now closing this out. If you find an api or some other app that is able to do it remotely, let me know and feel free to reopen.
