### ISSUE TITLE
Support for Relative Humidity Characteristic

### ISSUE THREAD

**Issue by webOSpinn** [grivkees/homebridge-carrier-infinity#53]
**Is your feature request related to a problem? Please describe:**
Currently the accessory doesn't support reporting the current relative humidity.

**Describe the solution you'd like:**
Implement the relative humidity characteristic which adds sensors to the home app to allow you to ask siri questions about the humidity.

This is the characteristic that applies:

HMCharacteristicTypeCurrentRelativeHumidity - Indicates the current relative humidity percentage.

**Describe alternatives you've considered:**
N/A

**Additional context:**
I've been playing around with "The Home Remote" app on Windows and iOS and it supports displaying the humidity and I believe it is using the same API.

**Comment by grivkees** [comment]
Hey! I should be able to add the RH as a separate accessory soon. (The rh is actually there as part of the thermostat accessory right now, but it’s hidden and not usable in automations.)

**Comment by webOSpinn** [comment]
Thanks for the quick reply. I love using this plugin.

My system also has a built-in humidifier. Not sure if that is something that is exposed by the API (state, humidity target, water pad life). It also uses the AC to dehumidify to a set level so maybe the state and humidity target could be exposed there as well. Obviously this should be a different issue if this can even be done so I'd be happy to enter another issue to investigate if this seems feasible.

**Comment by grivkees** [comment]
Yep, it’s definitely possible. It’s just a bit weird because the way the systems work is it has to be a permanent change that affects all activity profiles, so it would behave differently than the temperature settings (which revert after you take it off manual). Feel free to open another issue to track that.
