### ISSUE TITLE
Dehumidifying state causes unhandled exception

### ISSUE THREAD

**Issue by mhledwards** [grivkees/homebridge-carrier-infinity#8]
**Describe The Bug:**
When the system is in dehumidifying mode, the an error is thrown in the homebridge and the device appears unresponsive in Homekit.

**To Reproduce:**
Have a Carrier HVAC system enter dehumidfying mode.

**Expected behavior:**
While in dehumidfying mode, the state would either be displayed or gracefully ignored.

**Logs:**

`[23/05/2021, 19:06:37] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Current Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Unknown current state 'dehumidify'. See https://git.io/JtMGR for more info.`

**Plugin Config:**

{
    "username": "xxxxx",
    "password": "xxxxx",
    "holdBehavior": "forever",
    "platform": "CarrierInfinity",
    "_bridge": {
        "username": "xx:xx:xx:xx:xx:C1",
        "port": xxx65
    }
}

**Environment:**

* **Plugin Version**:*
homebridge-carrier-infinity v1.1.2-beta.1
 
* **Homebridge Version**: 
  v1.3.4
* **Node.js Version**: 
v14.15.5
* **NPM Version**: 
v6.14.11
* **Operating System**: 
Raspbian

**Comment by grivkees** [comment]
Thanks! I haven't been able to find any documentation on the possible values for this field. Didn't know about this one, so this is really helpful!

Does your system have a separate dehumidifier? Or is it set to overcool to dehumidify?

**Comment by mhledwards** [comment]
I do not believe it's a separate unit, in their app it says 'Overcool' is set to enabled.

Here's what the sales material says (probably of no use to you though).
- Humidity Tech
[https://www.carrier.com/residential/en/us/homeowner-resources/hvac-basics/keep_your_heat_and_humidity_at_a_manageable_level_with_carrier_technology.html](url)

- AC Unit
[https://www.carrier.com/residential/en/us/products/air-conditioners/24vna9/#](url)

- Furnace
[https://www.carrierenterprise.com/carrier-infinity-80-afue-90000-btuh-multipoise-gas-furnace-58tn0a090c21-20](url)


I did mess around with the different modes, and found a "fanonly" that threw an error:
`[23/05/2021, 21:12:29] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Unknown target state 'fanonly'. See https://git.io/JtMGR for more info.
`

I also grabbed a couple of pics from the control board if it means anything to you in terms of other possible states/modes:
![image](https://user-images.githubusercontent.com/76414511/119287063-56b07880-bc0b-11eb-9fb3-29464c9990dc.png)
![image](https://user-images.githubusercontent.com/76414511/119287081-5e701d00-bc0b-11eb-90fa-400076e9ef95.png)
![image](https://user-images.githubusercontent.com/76414511/119287100-66c85800-bc0b-11eb-98e4-f7c5ec4754df.png)
![image](https://user-images.githubusercontent.com/76414511/119287124-7182ed00-bc0b-11eb-9057-507ac8f529ba.png)

**Comment by grivkees** [comment]
Fixed and pushed 'dehumidify' and 'fanonly' support as v1.1.3. Let me know if you still have any issues. Really appreciate the help, and please keep submitting if you find anything else! Thanks!

**Comment by mhledwards** [comment]
Yea, no problem. I'm still seeing an error when I throw it into FanOnly mode. The mode states I have are Cool, Heat, Auto (Set Range), Fan Only, and Off.

`[24/05/2021, 00:05:28] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Unknown target state 'fanonly'. See https://git.io/JtMGR for more info.`

I can confirm the dehumidify seems to be working correctly.

**Comment by grivkees** [comment]
Will push new fix tomorrow for fanonly. New fix will make fanonly appear as 'off' until i get full fan control working. (fan will eventually show as separate accessory in homekit)

You're welcome!

**Comment by mhledwards** [comment]
Looks like it's fixed after updating and restarting homebridge. Kudos! :)
