### ISSUE TITLE
Per zone status

### ISSUE THREAD

**Issue by grivkees** [grivkees/homebridge-carrier-infinity#92]
https://www.reddit.com/r/homebridge/comments/mu0l9t/carrier_infinity_anyone_have_a_project_planned_or/h8i9uq4/

**Comment by grivkees** [comment]
Looks like this is the zoneconditioning field. It is “idle” when zone is off. And something like “active_cool” when on.

**Comment by Aqualung812** [comment]
If you need access to a multizone system for testing, I'm happy to send you my account info.

**Comment by grivkees** [comment]
@Aqualung812 thanks for the offer! Someone else sent me their api response, so I think I have it. When the PR attached here is merged in, you should be able to try out the latest @next, which will include the fix. If you see any issues, please reopen the issue.
